### ISSUE TITLE
Please undo your future::plan() when function exits

### ISSUE THREAD

**Issue by HenrikBengtsson** [insightsengineering/simIDM#105]
Congrats to the CRAN release. Author of Futureverse here.  I've got two comments, one smaller and one important one:

In

https://github.com/insightsengineering/simIDM/blob/dd4cebcc24d295312267e15b2a47707c2f99b675/R/corPFSOS.R#L317

instead of `max(1, parallelly::availableCores() - 1)`, you can use `parallelly::availableCores(omit = 1)`, which is mentioned on https://parallelly.futureverse.org/reference/availableCores.html.

Whenever you find yourself setting the future plan inside a function, make sure that your changes are undone when the function exits.  This is _very_ important, because the user might have set the future plan they prefer, and will become rather confused if their settings all of a sudden are changed.  If your function is called by another function or package, this might be quite tricky for the user to track down.  Also, since you're using all cores (but one)(*), after your function has been called, anything that rely on Futureverse will max out like that.  To fix this, please see Section 'For package developers' in [`help("plan", package = "future")`](https://future.futureverse.org/reference/plan.html).

(*) Which is a no-no on CRAN (**), but also elsewhere, e.g. https://www.jottr.org/2022/12/05/avoid-detectcores/
(**) Yes, `availableCores()` will return `2` when `R CMD check` is running, so you're saved by it here.

**Comment by holgstr** [comment]
Hi @HenrikBengtsson, thank you so much for taking a look and your considerate feedback. We will implement your comments as advised.
