### ISSUE TITLE
Add unit tests for correlation functions

### ISSUE THREAD

**Issue by holgstr** [insightsengineering/simIDM#92]
We need unit tests for all functions in corPFSOS.R

- [x] `survPFS`
- [x] `survOS`
- [x] `expvalPFSInteg`
- [x] `expvalOSInteg`
- [x] `p11Integ`
- [x] `log_p11`
- [x] `PFSOSInteg`
- [x] `survPFSOS`
- [x] `corTrans`

**Comment by danielinteractive** [comment]
:) We should have added those already - but no problem, doing it now quickly
